# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Organization.create(name: '董事長', is_sales: false)
Organization.create(name: '總經理', is_sales: false)
Organization.create(name: '創辦人', is_sales: false)
Organization.create(name: '經營企劃室', is_sales: false)
Organization.create(name: '營運管理處', is_sales: false)
Organization.create(name: '企溝處', is_sales: false)
Organization.create(name: '網路行銷部', is_sales: false)
Organization.create(name: '電子商務處', is_sales: false)
Organization.create(name: '資訊管理處', is_sales: false)
Organization.create(name: '業務發展處', is_sales: false)
Organization.create(name: '人力發展處', is_sales: false)
Organization.create(name: '財務部', is_sales: false)
Organization.create(name: '法務暨法令遵循部', is_sales: false)
Organization.create(name: '艾萊國際', is_sales: false)
Organization.create(name: '中聯集團/稽核室', is_sales: false)
Organization.create(name: '睿實科技', is_sales: false)
Organization.create(name: '台北營業處', is_sales: true)
Organization.create(name: '北二營業處', is_sales: true)
Organization.create(name: '北三營業處', is_sales: true)
Organization.create(name: '北四營業處', is_sales: true)
Organization.create(name: '北五營業處', is_sales: true)
Organization.create(name: '北六營業處', is_sales: true)
Organization.create(name: '新板通訊處', is_sales: true)
Organization.create(name: '新北營業處', is_sales: true)
Organization.create(name: '台北南京通訊處', is_sales: true)
Organization.create(name: '台北大同通訊處', is_sales: true)
Organization.create(name: '台北南西通訊處', is_sales: true)
Organization.create(name: '桃園營業處', is_sales: true)
Organization.create(name: '新竹營業處', is_sales: true)
Organization.create(name: '台中營業處', is_sales: true)
Organization.create(name: '中二營業處', is_sales: true)
Organization.create(name: '中三營業處', is_sales: true)
Organization.create(name: '中四營業處', is_sales: true)
Organization.create(name: '中五營業處', is_sales: true)
Organization.create(name: '中六營業處', is_sales: true)
Organization.create(name: '中八營業處', is_sales: true)
Organization.create(name: '中九營業處', is_sales: true)
Organization.create(name: '中十營業處', is_sales: true)
Organization.create(name: '中十一營業處', is_sales: true)
Organization.create(name: '中十二營業處', is_sales: true)
Organization.create(name: '中十三營業處', is_sales: true)
Organization.create(name: '大里營業處', is_sales: true)
Organization.create(name: '草屯通訊處', is_sales: true)
Organization.create(name: '彰化營業處', is_sales: true)
Organization.create(name: '員林營業處', is_sales: true)
Organization.create(name: '雲林營業處', is_sales: true)
Organization.create(name: '嘉義營業處', is_sales: true)
Organization.create(name: '南二營業處', is_sales: true)
Organization.create(name: '高雄營業處', is_sales: true)
Organization.create(name: '高二營業處', is_sales: true)
Organization.create(name: '高雄鼓山通訊處', is_sales: true)
Organization.create(name: '花蓮通訊處', is_sales: true)
Organization.create(name: '台東通訊處', is_sales: true)
